# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(verbose_name='exam date')),
                ('exam_type', models.CharField(max_length=200)),
                ('exam_doc', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=200)),
                ('hospital_no', models.IntegerField()),
                ('patient_sex', models.CharField(max_length=10)),
                ('patient_age', models.IntegerField()),
                ('exam_Dx', models.CharField(max_length=200)),
                ('exam_Bx', models.BooleanField(default=True)),
                ('Bx_result', models.CharField(max_length=200)),
                ('follow_up', models.IntegerField()),
            ],
        ),
    ]
