# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_auto_20160923_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(auto_now=True, verbose_name='검사 날짜'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='patient_birth',
            field=models.DateField(auto_now=True, verbose_name='생일'),
        ),
    ]
