# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_auto_20160923_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-exam_date']},
        ),
        migrations.AlterField(
            model_name='exam',
            name='Bx_result',
            field=models.CharField(blank=True, max_length=200, verbose_name='조직검사 결과'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(verbose_name='검사 날짜'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='patient_birth',
            field=models.DateField(verbose_name='생일'),
        ),
    ]
