# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_auto_20160924_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Bx_result',
            field=models.CharField(max_length=200, verbose_name='조직검사 결과'),
        ),
    ]
