# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_auto_20160926_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Bx_result',
            field=models.CharField(blank=True, max_length=200, verbose_name='조직검사 결과'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='follow_up',
            field=models.IntegerField(blank=True, verbose_name='추적검사 기간'),
        ),
    ]
