# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_auto_20160926_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='follow_up',
            field=models.IntegerField(default=24, verbose_name='추적검사 기간'),
        ),
    ]
