# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0009_auto_20160927_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('upper', 'EGD'), ('lower', 'Colonoscopy'), ('sig', 'Sigmoidoscopy')], default='upper', max_length=10, verbose_name='내시경 종류'),
        ),
    ]
