# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_auto_20160927_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_Bx',
            field=models.CharField(choices=[('Bx', 'Bx'), ('Polypectomy', 'Polypectomy'), ('EMR', 'EMR'), ('ForeignBody', 'Foreign Body Remove'), ('BleedingControl', 'Bleeding Control')], default='Bx', max_length=20, verbose_name='시술'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='follow_up',
            field=models.IntegerField(blank=True, verbose_name='추적검사 기간'),
        ),
    ]
