# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_auto_20160929_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_place',
            field=models.CharField(choices=[('inpatient', '입원'), ('outpatient', '외래')], default='outpatient', max_length=20, verbose_name='외래/입원'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.CharField(choices=[('national', '건진'), ('hospital', '진료')], default='national', max_length=30, verbose_name='건진/진료'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_doc',
            field=models.CharField(choices=[('lyj', '이영재'), ('ksi', '김신일')], default='ksi', max_length=30, verbose_name='의사'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='patient_sex',
            field=models.CharField(choices=[('m', '남자'), ('f', '여자')], default='m', max_length=10, verbose_name='성별'),
        ),
    ]
