# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 16:58
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0014_auto_20161004_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_Bx',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bx', 'Bx'), ('Polypectomy', 'Polypectomy'), ('EMR', 'EMR'), ('ForeignBody', 'Foreign Body Remove'), ('BleedingControl', 'Bleeding Control')], max_length=20, verbose_name='시술'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('upper', 'EGD'), ('lower', 'Colonoscopy'), ('sig', 'Sigmoidoscopy')], max_length=10, verbose_name='내시경 종류'),
        ),
    ]
