# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0016_auto_20161004_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.CharField(choices=[('건진', '건진'), ('진료', '진료')], default='national', max_length=30, verbose_name='건진/진료'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_doc',
            field=models.CharField(choices=[('이영재', '이영재'), ('김신일', '김신일')], default='ksi', max_length=30, verbose_name='의사'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_place',
            field=models.CharField(choices=[('입원', '입원'), ('외래', '외래')], default='outpatient', max_length=20, verbose_name='외래/입원'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EGD', 'EGD'), ('Colonoscopy', 'Colonoscopy'), ('Sigmoidoscopy', 'Sigmoidoscopy')], max_length=10, verbose_name='내시경 종류'),
        ),
    ]
