# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_auto_20161005_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_Bx',
            new_name='exam_procedure',
        ),
    ]
