# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0019_auto_20161005_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='hospital_no',
            field=models.CharField(max_length=10, verbose_name='환자등록 번호'),
        ),
    ]
