# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:48
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0020_auto_20161005_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EGD', 'EGD'), ('Colonoscopy', 'Colonoscopy'), ('Sigmoidoscopy', 'Sigmoidoscopy')], max_length=20, verbose_name='내시경 종류'),
        ),
    ]
