# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0023_auto_20161006_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.CharField(choices=[('건진', '건진'), ('진료', '진료')], default='건진', max_length=30, verbose_name='건진/진료'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_doc',
            field=models.CharField(choices=[('이영재', '이영재'), ('김신일', '김신일')], default='김신일', max_length=30, verbose_name='의사'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_place',
            field=models.CharField(choices=[('입원', '입원'), ('외래', '외래')], default='외래', max_length=20, verbose_name='외래/입원'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='patient_sex',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], default='M', max_length=10, verbose_name='성별'),
        ),
    ]
