# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0025_auto_20161006_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Bx_result',
            field=models.CharField(default='입력해 주세요', max_length=200, verbose_name='조직검사 결과'),
        ),
    ]
