# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 06:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0030_exam_phone_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_procedure',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Bx', 'Bx'), ('CLO', 'CLO'), ('Polypectomy', 'Polypectomy'), ('EMR', 'EMR'), ('ForeignBody', 'Foreign Body Remove'), ('BleedingControl', 'Bleeding Control'), ('PEG', 'PEG')], max_length=20, verbose_name='시술'),
        ),
    ]
