# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0031_auto_20161007_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='re_visit',
            field=models.BooleanField(default=False, verbose_name='재방문'),
        ),
    ]
