# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0032_exam_re_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(default=datetime.date.today, verbose_name='검사 날짜'),
        ),
    ]
