# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0033_auto_20161013_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.CharField(choices=[('건진', '건진'), ('진료', '진료'), ('건진+진료', '건진+진료')], default='건진', max_length=30, verbose_name='건진/진료'),
        ),
    ]
