# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0034_auto_20161019_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endoscopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='검사 날짜')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'EGD'), ('C', 'Colonoscopy'), ('S', 'Sigmoidoscopy')], max_length=20, verbose_name='내시경 종류')),
                ('doc', models.CharField(choices=[('이영재', '이영재'), ('김신일', '김신일')], default='김신일', max_length=10, verbose_name='의사')),
                ('source', models.CharField(choices=[('건진', '건진'), ('진료', '진료'), ('건진+진료', '건진+진료')], default='건진', max_length=10, verbose_name='건진/진료')),
                ('place', models.CharField(choices=[('입원', '입원'), ('외래', '외래')], default='외래', max_length=10, verbose_name='외래/입원')),
                ('Dx', models.CharField(max_length=200, verbose_name='내시경 진단명')),
                ('procedure', multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Bx', 'Bx'), ('CLO', 'CLO'), ('Polypectomy', 'Polypectomy'), ('EMR', 'EMR'), ('ForeignBody', 'Foreign Body Remove'), ('BleedingControl', 'Bleeding Control'), ('PEG', 'PEG')], max_length=20, verbose_name='시술')),
                ('Bx_result', models.CharField(max_length=200, verbose_name='조직검사 결과')),
                ('Bx_result_call', models.CharField(default='조직검사 결과 전화 통보함', max_length=50, verbose_name='조직검사 전화 통보 내용')),
                ('followup_period', models.IntegerField(default=0, verbose_name='추적검사 기간')),
                ('re_visit_call', models.CharField(default='이번달 방문하기로 함', max_length=50, verbose_name='재방문 전화 통화 내용')),
                ('re_visit', models.BooleanField(default=False, verbose_name='재방문')),
                ('re_visit_date', models.DateField(verbose_name='재방문 날짜')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='환자 이름')),
                ('hospital_no', models.CharField(max_length=10, verbose_name='환자등록 번호')),
                ('sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], default='M', max_length=10, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생일')),
                ('phone', models.CharField(default='010-', max_length=15, verbose_name='전화번호')),
                ('adress', models.CharField(max_length=30, verbose_name='주소')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='Bx_result_call',
            field=models.CharField(default='.', max_length=100, verbose_name='조직검사 결과 알려주었나요?'),
        ),
    ]
