# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0036_endoscopy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endoscopy',
            name='Bx_result',
            field=models.CharField(default='', max_length=200, verbose_name='조직검사 결과'),
        ),
        migrations.AlterField(
            model_name='endoscopy',
            name='Bx_result_call',
            field=models.CharField(default='', max_length=50, verbose_name='조직검사 전화 통보 내용'),
        ),
        migrations.AlterField(
            model_name='endoscopy',
            name='followup_period',
            field=models.IntegerField(default=24, verbose_name='추적검사 기간'),
        ),
        migrations.AlterField(
            model_name='endoscopy',
            name='re_visit_call',
            field=models.CharField(default='', max_length=50, verbose_name='재방문 전화 통화 내용'),
        ),
        migrations.AlterField(
            model_name='endoscopy',
            name='re_visit_date',
            field=models.DateField(default='1900-01-01', verbose_name='재방문 날짜'),
        ),
    ]
