# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-17 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0037_auto_20171218_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='address',
        ),
    ]
