# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-09 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0039_auto_20180208_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
