# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-13 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0041_auto_20180211_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoscopy',
            name='sleep',
            field=models.CharField(choices=[('수면', '수면'), ('일반', '일반')], default='수면', max_length=6, verbose_name='수면/일반'),
        ),
    ]
