# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0042_endoscopy_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoscopy',
            name='followup_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 16, 23, 54, 62752), verbose_name='추적검사날짜'),
        ),
    ]
