# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0043_endoscopy_followup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endoscopy',
            name='followup_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 0, 25, 43, 808983), verbose_name='추적검사날짜'),
        ),
    ]
